### ISSUE TITLE
chruby: /Users/ken/.rubies/ruby-3.1.2/bin/ruby not executable failed

### ISSUE THREAD

**Issue by kenaitian** [rubyonmac/rubyonmac-issues#10]
Hi there. Thanks for buying Ruby on Mac!

If you bought Ruby on Mac Prime and it failed while running in normal mode,
please run it in reset mode first before reporting a bug.

**In which version of Ruby on Mac did you find the bug?**
Basic, Plus, or Prime?
Basic

**Describe the bug**

You have the latest version of Ruby
chruby: /Users/ken/.rubies/ruby-3.1.2/bin/ruby not executable
failed

**Details about your Mac**
Before you ran the script for the first time, did you already have development tools like Homebrew installed, or did you run it on a fresh and clean macOS?

1. I started from a clean slate following your basic documentation.
2. I executed "brew doctor" and it's says "Your system is ready to brew."
3. I executed "cd ~/Downloads/rubyonmac-basic
/usr/bin/env bash ~/Downloads/rubyonmac-basic/rom-basic 2>&1 | tee ~/rom-basic.log" and it does show on log that "Your Homebrew installation is good to go."
4. I reinstalled the CommandLineTools (CLT) by executing "xcode-select --install," "rm -rf ~/.rubies," "brew uninstall chruby ruby-install," and then ran the Ruby on Mac script again but still same error above after step 3 again.

**Please attach the Ruby on Mac log file**
The log file will be called either `rom-basic.log`, or `rom-plus.log`, or `rom-prime.log`. You can find it in your Mac's Home folder.
[rom-basic.log](https://github.com/rubyonmac/rubyonmac-issues/files/9077622/rom-basic.log)

**Comment by monfresh** [comment]
Hi @kenaitian. Thanks for buying Ruby on Mac! It looks like you bought it a month ago, and I've improved the documentation since then. Look out for an email from me soon with the latest version.

In the meantime, can you try removing the rubies with `sudo`:

```
sudo rm -rf ~/.rubies
```

then quit and restart Terminal, and try running the script again.

**Comment by kenaitian** [comment]
@monfresh yes, I did download the same day and everything was working fine. I had to upgrade SSD and Time Machine reset and that's when I started getting these errors when trying again. I did sudo and everything else with the original zip file but still errs. I got your email about the latest zip and I'll keep you posted when that works.

**Comment by kenaitian** [comment]
Ultimate version works fine

**Comment by monfresh** [comment]
Great! I'm glad you got it working.
