### ISSUE TITLE
Compiling ruby 3.1.2 failed!

### ISSUE THREAD

**Issue by nolandonley14** [rubyonmac/rubyonmac-issues#13]
**In which version of Ruby on Mac did you find the bug?**
I have Ruby on Mac Prime

**Describe the bug**
After running reset mode, I ran the script in normal mode and receive "!!! Compiling ruby 3.1.2 failed!" error

**Details about your Mac**
MacBook Pro (2021) - M1 - macOS 12.6
Before running the first time, I already had homebrew install and other development tools for react native development. My main issue is with cocoapods on M1, and somewhere along the line of debugging, it became unusable, so I decided to try ruby on mac. I first ran the reset script then the normal script which produces the following log file.

[rom-prime.log](https://github.com/rubyonmac/rubyonmac-issues/files/9655805/rom-prime.log)

**Please attach the Ruby on Mac log file**
See attached above

**Comment by monfresh** [comment]
Hi @nolandonley14. Thanks for buying Ruby on Mac! It looks like there might be a bug in my script. The part where it was supposed to detect v14 of the command line tools didn't work for some reason.

Can you please try quitting and relaunching your terminal, and then run the script again with `rom`?

**Comment by monfresh** [comment]
I just fixed the bug. Can you please try with the latest update? Here are the steps to update:


1. Remove the `rubyonmac-prime` folder that's in your Downloads folder
2. Download the latest version to your Downloads folder by clicking the link in the email you received from Paddle.
3. Unzip the file if necessary
4. Check that the `VERSION` file says 1.9.3
5. Run `romup` in your terminal

**Comment by monfresh** [comment]
Hi @nolandonley14. Just following up to see if the latest version worked for you.

**Comment by monfresh** [comment]
Since I haven't heard back, I'm going to close this assuming everything is working now. If not, feel free to reopen this.
