### ISSUE TITLE
Issue with running ROM - Apple M1

### ISSUE THREAD

**Issue by tiffzny** [rubyonmac/rubyonmac-issues#18]
Hi there. Thanks for buying Ruby on Mac!

If you bought Ruby on Mac Basic and it failed the first time, please 
read through the troubleshooting guide first before reporting a bug.

If you bought Ruby on Mac Prime or Pro and it failed while running in normal mode, please run it in reset mode first before reporting a bug.

**In which version of Ruby on Mac did you find the bug?**
Prime

**Describe the bug**
I had installed Ruby on Mac successfully and used it for a bit, though not for awhile (about a year?). Went to use "jekyll" and it failed, so I tried running "rom" to update things, which also failed. At this point, reading through the docs and troubleshooting, I tried an install on RESET mode. It failed around homebrew which I expected from the docs, so I ran it again, which succeeded. Great!

I quit & restarted terminal, and then ran "rom" in the terminal and .. it ended with an error.

I'm trying to update a simple website built with Jekyll and I can't get the jekyll bit to run. I had originally gotten it set-up by using ROM.

**Details about your Mac**
ROM had already been installed, so homebrew was already installed. It's not a fresh-and-clean Mac, but I'd hardly call myself a "developer" so not much going on in it.
Currently running MacOS Ventura, Version 13.5 (22G74) (yeah I should probably update)
Apple M1 Pro Chip

**Please attach the Ruby on Mac log file**
Attached rom-prime.log

[rom-prime.log](https://github.com/rubyonmac/rubyonmac-issues/files/14826442/rom-prime.log)

**Comment by monfresh** [comment]
Hi @tiffzny. You are running a super old version of Ruby on Mac. Please email me at moncef [at] rubyonmac [dot] dev and I'll send you instructions for updating to the latest version.

**Comment by tiffzny** [comment]
Well, that'll do it. Thanks for the note, email incoming.
