### ISSUE TITLE
Script seems to run fine in reset, but ruby not working

### ISSUE THREAD

**Issue by geoffsdavis** [rubyonmac/rubyonmac-issues#2]
**In which version of Ruby on Mac did you find the bug?**
Prime?

**Describe the bug**
Hi, the script seems to be running fine in reset mode, and reports "All done!" at the end, but 'ruby -v' still shows my old 2.6.3, and chruby appears to not have been installed. I see this every time I fire up a Terminal window:

```
/etc/zshrc_Apple_Terminal:35: parse error near 'done'
/usr/local/share/chruby/chruby.sh:6: parse error near 'done'
/usr/local/share/chruby/auto.sh:17: parse error near 'done'
/Users/[me]/.zshrc:16: command not found: chruby
/Users/[me]/.zshrc:18: command not found: chruby
```

I'm attaching the log file. In addition, here are some troubleshooting steps I originally took:
1) At first 'brew doctor' was reporting various linking errors and obsolete headers, but I got that cleaned up until it reported 'Your system is ready to brew.'
2) I was on Bash. I moved to Zch, per your instructions. This did seem to help somewhere, but still didn't ultimately resolve the issue.
3) I don't think I have anything too weird in my .zprofile or .zshrc, other than usual aliases, prompts, and other goodies.
3) I've been quitting and restarting Terminal during all this.

**Details about your Mac**
My Mac is a late-2014 27" iMac, running Big Sur 11.6.4. I did have Homebrew installed before. I don't remember which version. I had previous versions of Ruby such as 2.6.3.

**Please attach the Ruby on Mac log file**
Attached.

Please advise.

Thanks!
Geoff

[rom-prime.log](https://github.com/rubyonmac/rubyonmac-issues/files/8114521/rom-prime.log)

Also, brew seems to think I already have chruby:

```
Geoff-iMac: ~/Documents >> brew install chruby
Warning: chruby 0.3.9 is already installed and up-to-date.
To reinstall 0.3.9, run:
  brew reinstall chruby
Geoff-iMac: ~/Documents >> brew info chruby
chruby: stable 0.3.9 (bottled), HEAD
Ruby environment tool
https://github.com/postmodern/chruby#readme
/usr/local/Cellar/chruby/0.3.9 (12 files, 51.2KB) *
  Poured from bottle on 2022-02-21 at 23:41:21
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/chruby.rb
License: MIT
==> Options
--HEAD
	Install HEAD version
==> Caveats
Add the following to the ~/.bash_profile or ~/.zshrc file:
  source /usr/local/opt/chruby/share/chruby/chruby.sh

To enable auto-switching of Rubies specified by .ruby-version files,
add the following to ~/.bash_profile or ~/.zshrc:
  source /usr/local/opt/chruby/share/chruby/auto.sh
==> Analytics
install: 3,711 (30 days), 9,902 (90 days), 30,165 (365 days)
install-on-request: 3,701 (30 days), 9,867 (90 days), 30,047 (365 days)
build-error: 0 (30 days)
```

**Comment by geoffsdavis** [comment]
Any update on this? Thanks.

Geoff

**Comment by monfresh** [comment]
Sorry @geoffsdavis! I just saw this! I must not have set up notifications. I'm looking into it now.

**Comment by monfresh** [comment]
@geoffsdavis I don't see anything wrong in the log, so I think it's something specific to how your Terminal is set up. That error from `/etc/zshrc_Apple_Terminal` seems suspicious.

I think the best way to troubleshoot this is over Zoom. Here's a link to [schedule a free session](https://savvycal.com/monfresh/office-hours?d=30&from=2022-03-07&via=moncef). My kids are home sick today, so the earliest I would be available is tomorrow. If none of the available times work for you, let me know and we can find a time that works for both of us.

And sorry again for not seeing this until now. In the future, if I don't respond within a day, please feel free to email me or ping me on [Twitter](https://www.twitter.com/monfresh).

**Comment by monfresh** [comment]
HI @geoffsdavis. Since I haven't heard back, I'm assuming you were able to fix the issue. Feel free to reopen or contact me directly if you're still seeing the issue.
