### ISSUE TITLE
!!! Compiling ruby 3.1.2 failed!

### ISSUE THREAD

**Issue by TimHi** [rubyonmac/rubyonmac-issues#6]
**In which version of Ruby on Mac did you find the bug?**
Prime

**Describe the bug**
Building Ruby results in an error, CLT are up to date.

**Details about your Mac**
Before you ran the script for the first time, did you already have development tools like Homebrew installed, or did you run it on a fresh and clean macOS?
Homebrew was installed, M1 chip.

**Please attach the Ruby on Mac log file**
[rom-prime.log](https://github.com/rubyonmac/rubyonmac-issues/files/8646087/rom-prime.log)

**Comment by monfresh** [comment]
Hi @TimHi. Thanks for buying Ruby on Mac!

From the log, it looks like your previous development tools weren't properly configured. I would recommend running in reset mode if you haven't tried that already.

**Comment by TimHi** [comment]
Thank you for the quick response, I ran the reset mode (permission issue when removing .gem, solved that) and now it ran through and looks good!

**Comment by monfresh** [comment]
Awesome! I'm glad it all worked out. Thanks for letting me know about the permission issue when removing .gem. I'll fix it.
