### ISSUE TITLE
Compiling ruby 3.1.2 failed

### ISSUE THREAD

**Issue by elmnt** [rubyonmac/rubyonmac-issues#9]
Hi there. Thanks for buying Ruby on Mac!

If you bought Ruby on Mac Prime and it failed while running in normal mode,
please run it in reset mode first before reporting a bug.

**In which version of Ruby on Mac did you find the bug?**
Basic

**Describe the bug**
Terminal message as follows:
2 errors generated.
make: *** [compile.o] Error 1
!!! Compiling ruby 3.1.2 failed!
failed

**Details about your Mac**
Already had Homebrew installed

**Please attach the Ruby on Mac log file**
[rom-basic.log](https://github.com/rubyonmac/rubyonmac-issues/files/8941185/rom-basic.log)

**Comment by elmnt** [comment]
Update: I updated the Command Line Tools, as indicated in the log, and started over. Working fine now, thank you!

**Comment by monfresh** [comment]
Great! I'm glad you figure it out.
